services:
  aplicacion_python:
    container_name: aplicacion_python
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=aplicacion_mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DB=aplicacion
      - MYSQL_PORT=3306
    depends_on:
      - aplicacion_mysql

  aplicacion_mysql:
    image: mysql:8.0
    container_name: aplicacion_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=aplicacion

  aplicacion_php:
    image: phpmyadmin/phpmyadmin:latest
    container_name: aplicacion_php
    ports:
      - "80:80"
    environment:
      - PMA_HOST=aplicacion_mysql
      - PMA_USER=root
      - PMA_PASSWORD=1234
      - PMA_ARBITRARY=1
