version: '3.8'
services:
  mysql-master1:
    image: mysql:8.0
    container_name: mysql_maestro1
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=replica
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=replica
    networks:
      - backend
    volumes:
      - ./mysql-data1:/var/lib/mysql        # Volumen para datos de MySQL
      - ./mysql-config1:/etc/mysql/conf.d   # Volumen para configuración, si es necesario

  mysql-master2:
    image: mysql:8.0
    container_name: mysql_maestro2
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=replica
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=replica
    networks:
      - backend
    volumes:
      - ./mysql-data2:/var/lib/mysql        # Volumen para datos de MySQL
      - ./mysql-config2:/etc/mysql/conf.d   # Volumen para configuración, si es necesario

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_m
    ports:
      - 8081:80
    environment:
      - PMA_HOSTS="nginxPrueba" # Apunta a Nginx como host
      - PMA_PORT=80           # Usa el puerto del balanceador
      - PMA_ARBITRARY=1
    networks:
      - backend
  
  phpmyadmin2:
    image: phpmyadmin:latest
    container_name: phpmyadmin_m2
    ports:
      - 8082:80
    environment:
      - PMA_HOSTS="nginxPrueba" # Apunta a Nginx como host
      - PMA_PORT=80           # Usa el puerto del balanceador
      - PMA_ARBITRARY=1
    networks:
      - backend
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginxPrueba
    ports:
      - "80:80"
    depends_on:
      - mysql-master1
      - mysql-master2
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql-data1:    # Volumen para mysql-master1
  mysql-data2:    # Volumen para mysql-master2
  mysql-config1:  # Volumen para configuraciones de mysql-master1 (si lo necesitas)
  mysql-config2:  # Volumen para configuraciones de mysql-master2 (si lo necesitas)
