services:
  # Contenedor para ElasticSearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    networks:
      - elk
    volumes:
      - ./esdata:/usr/share/elasticsearch/data

networks:
  elk:
    driver: bridge

volumes:
  esdata:
    driver: local